import { Platform, StyleSheet } from 'react-native';

export const COLORS = {
  bg0: '#0b1020',
  bg1: '#111827',
  accent: '#5eead4',
  accentSoft: '#99f6e4',
  text: '#f8fafc',
  muted: '#94a3b8',
  card: 'rgba(15,23,42,0.65)',
  border: 'rgba(255,255,255,0.1)',
  error: '#fecaca',
  warn: '#fde68a',
};

export const styles = StyleSheet.create({
  gradient: { flex: 1 },
  scroll: { padding: 16, paddingBottom: 48 },
  brand: { color: COLORS.accentSoft, letterSpacing: 3, fontSize: 11, fontWeight: '700' },
  headline: { marginTop: 6, fontSize: 24, fontWeight: '700', color: COLORS.text },
  sub: { marginTop: 6, color: COLORS.muted, lineHeight: 20, fontSize: 13 },
  label: { color: '#cbd5e1', fontSize: 12, marginBottom: 4, fontWeight: '600' },
  input: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: COLORS.text,
    backgroundColor: 'rgba(15,23,42,0.75)',
    fontSize: 15,
  },
  tabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 12, marginBottom: 4 },
  tab: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  tabActive: { backgroundColor: '#fff' },
  tabText: { color: '#e2e8f0', fontSize: 12, fontWeight: '600' },
  tabTextActive: { color: '#0f172a' },
  card: {
    marginTop: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cardTitle: { color: COLORS.text, fontSize: 17, fontWeight: '700', marginBottom: 10 },
  sectionLabel: {
    color: COLORS.accentSoft,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  primary: {
    marginTop: 8,
    backgroundColor: COLORS.accent,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: 'center',
  },
  primaryText: { color: '#0f172a', fontWeight: '700', fontSize: 14 },
  secondary: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    paddingVertical: 11,
    borderRadius: 14,
    alignItems: 'center',
  },
  secondaryText: { color: '#e2e8f0', fontWeight: '700', fontSize: 13 },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  chipActive: { backgroundColor: COLORS.accent, borderColor: COLORS.accent },
  chipText: { color: '#e2e8f0', fontSize: 12, fontWeight: '600' },
  chipTextActive: { color: '#0f172a' },
  mono: {
    marginTop: 10,
    color: '#a5f3fc',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
  },
  body: { color: '#cbd5e1', lineHeight: 22, fontSize: 14 },
  error: { color: COLORS.error, marginTop: 8, fontSize: 13, lineHeight: 18 },
  warn: { color: COLORS.warn, marginTop: 8, fontSize: 13, lineHeight: 18 },
  ok: { color: '#86efac', marginTop: 8, fontSize: 13, lineHeight: 18 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(2,8,18,0.88)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    maxHeight: '90%',
    borderRadius: 20,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 18,
  },
});

export const NAV_TABS = [
  { id: 'lab', label: 'Inicio' },
  { id: 'roots', label: 'Raíces' },
  { id: 'poly', label: 'Polinomios' },
  { id: 'interp', label: 'Interp.' },
  { id: 'concepts', label: 'Conceptos' },
  { id: 'about', label: 'Acerca' },
];

export const ROOT_METHODS = [
  { id: 'bisection', label: 'Bisección' },
  { id: 'false_position', label: 'Pos. falsa' },
  { id: 'newton_raphson', label: 'Newton' },
  { id: 'secant', label: 'Secante' },
  { id: 'fixed_point', label: 'Punto fijo' },
];
